name: Update Conda-Forge Feedstock

on:
  release:
    types: [published]

jobs:
  update-feedstock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install ruamel.yaml gitpython

      - name: Update feedstock meta.yaml
        env:
          FEEDSTOCK_REPO: "https://github.com/conda-forge/fedfred-feedstock.git"
          PACKAGE_VERSION: ${{ github.event.release.tag_name }}
        run: |
          python .github/scripts/update_feedstock.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone $FEEDSTOCK_REPO feedstock
          cp updated_meta.yaml feedstock/recipe/meta.yaml
          cd feedstock
          git checkout -b update-${{ github.event.release.tag_name }}
          git add recipe/meta.yaml
          git commit -m "Update to version ${{ github.event.release.tag_name }}"
          git push origin update-${{ github.event.release.tag_name }}

      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.FEEDSTOCK_TOKEN }}
          commit-message: "Update to version ${{ github.event.release.tag_name }}"
          branch: update-${{ github.event.release.tag_name }}
          title: "Update to version ${{ github.event.release.tag_name }}"
          body: "This PR updates the feedstock to version ${{ github.event.release.tag_name }}."
